config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
  get '/display', to:'people#display'

end

app/models/person.rb
class Person < ActiveRecord::Base
    # restrictions for what to enter on the form
    validates :name, presence: true
    validates :weight, presence: true
    validates :height, presence: true
    validates :color, presence: true, format: { with: /\A[a-zA-Z]+\z/}
    validates :font, presence:true
    validates :happy, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end
  
  
  helper_method :display
  def display
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        # format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        # format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        # format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        # format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :weight, :height, :color, :font, :happy)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<!--display for error message-->
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--The inputs of the form-->
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight, "Weight (in kilograms)" %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height, "Height (in centimeters)" %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :color, "Eye Color" %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :font %><br>
    <%= f.select :font, ['Times New Roman', 'Tahoma', 'Arial', 'Verdana', 'Comic Sans MS'] %>
  </div>
  <div class="field">
    <%= f.label :happy, "Happiness Scale" %><br>
    <%= f.select :happy,  (1..10)%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/display.html.erb
<h1>Display</h1>



<!--iterating through the person.id-->
<% @people.each do |person| %>
    <p style= "font-family: <%= person.font %>;">Person #<%=person.id%> in the database.</p>
    <!--boxes in the display page-->
    <p style= "width:<%= person.weight %>mm;
    height:<%= person.height %>px;
    background-color: <%= person.color %>;
    font-family: <%= person.font %>;
    font-size: <%= Math.sqrt(person.weight)*3 %>px;
    border:1px solid #000;
    position:relative;
    animation-name: happy;
    animation-duration: 1s;
    animation-iteration-count: <%=person.happy%>;"> <%= person.name %>'s box with <%=person.happy%> happy jumps </p>
<% end %>

<!--button for back to people and scrolls with the page in a fixed spot-->
<div style= "position:fixed;
top: 10cm; 
right: 3cm;"> 
<%= button_to 'Back to people', people_path, :class => "submit", :method => :get %></div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Continue', people_path %>

app/views/people/index.html.erb
<h1>Listing People</h1>

<table>
  <!--table heading-->
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Weight (in kilograms)</th>
      <th>Height (in centimeters)</th>
      <th>Eye Color</th>
      <th>Font</th>
      <th>Happiness Scale</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>

    <% @people.each do |person| %>
    <!--reading the data to fill in the table-->
      <tr>
        <td><%= person.id %></td>
        <td><%= person.name %></td>
        <td><%= person.weight %></td>
        <td><%= person.height %></td>
        <td><%= person.color %></td>
        <td><%= person.font %></td>
        <td><%= person.happy %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= button_to 'New Person', new_person_path, :class => "submit", :method => :get %>
<div style="margin-top:5mm;"><%= button_to 'Display', '/display', :class => "submit", :method => :get %></div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back to people', people_path %>

app/views/people/show.html.erb
<p>Welcome to the club you are person #<%= @person.id %></p>
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Weight (in kilograms):</strong>
  <%= @person.weight %>
</p>

<p>
  <strong>Height (in centimeters):</strong>
  <%= @person.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @person.color %>
</p>

<p>
  <strong>Font:</strong>
  <%= @person.font %>
</p>

<p>
  <strong>Happiness Scale:</strong>
  <%= @person.happy %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Continue', people_path %>